// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIlrUsnhinwNGKO-PGDXoDZ7lmRCL5jrw',
    appId: '1:922879540431:web:e09af24a58309649b0cbba',
    messagingSenderId: '922879540431',
    projectId: 'mctq-quiz-hub',
    authDomain: 'mctq-quiz-hub.firebaseapp.com',
    storageBucket: 'mctq-quiz-hub.firebasestorage.app',
    measurementId: 'G-19W4QP2791',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwBVAqZ5l3q5WluBbvz89hIk8UfW51na8',
    appId: '1:922879540431:android:e6aada1e53086132b0cbba',
    messagingSenderId: '922879540431',
    projectId: 'mctq-quiz-hub',
    storageBucket: 'mctq-quiz-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuUh8YxTjbd3qtJLDT8CsU8S6dV7aJkMs',
    appId: '1:922879540431:ios:5117e89ffe168385b0cbba',
    messagingSenderId: '922879540431',
    projectId: 'mctq-quiz-hub',
    storageBucket: 'mctq-quiz-hub.firebasestorage.app',
    iosClientId: '922879540431-k2ggpvqtai91l5ri2h41sr838pe2i96f.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuUh8YxTjbd3qtJLDT8CsU8S6dV7aJkMs',
    appId: '1:922879540431:ios:5117e89ffe168385b0cbba',
    messagingSenderId: '922879540431',
    projectId: 'mctq-quiz-hub',
    storageBucket: 'mctq-quiz-hub.firebasestorage.app',
    iosClientId: '922879540431-k2ggpvqtai91l5ri2h41sr838pe2i96f.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIlrUsnhinwNGKO-PGDXoDZ7lmRCL5jrw',
    appId: '1:922879540431:web:95dc8592a297da22b0cbba',
    messagingSenderId: '922879540431',
    projectId: 'mctq-quiz-hub',
    authDomain: 'mctq-quiz-hub.firebaseapp.com',
    storageBucket: 'mctq-quiz-hub.firebasestorage.app',
    measurementId: 'G-D9BVB3CV8Q',
  );

}